-- ============================================================
-- Migration: caches the structured JSON output of the analyze-project
-- Edge Function (تحلیل هوشمند), keyed by project + AI provider, so a
-- repeat view of an unchanged project reuses the previous (paid) AI
-- call instead of re-generating it. source_data_at records the newest
-- source-row timestamp (check_ins/client_reports/quick_win_decisions/
-- quick_win_progress) the cached analysis was actually based on, so
-- the Edge Function can tell a genuinely stale cache entry from a
-- fresh one and only regenerate when the underlying data changed.
--
-- Admin-only, matching every other read of this cross-organization
-- data: only an admin should ever see one org's data folded together
-- with another's, whether live or cached.
-- ============================================================

create table if not exists ai_analyses (
    id bigint generated by default as identity primary key,
    project_name text not null,
    provider text not null,
    analysis_json jsonb not null,
    source_data_at timestamptz not null,
    created_at timestamptz not null default now()
);

create index if not exists ai_analyses_project_provider_created_at_idx
    on ai_analyses (project_name, provider, created_at desc);

alter table ai_analyses enable row level security;

drop policy if exists "admin full access on ai_analyses" on ai_analyses;
create policy "admin full access on ai_analyses" on ai_analyses
    for all using (is_admin()) with check (is_admin());
