-- ============================================================
-- Migration: turns «پیگیری اجرای Quick Win» into an issue-tracker-style
-- checklist instead of just a single progress percentage. Each selected
-- Quick Win can now have any number of discrete tasks, each with its own
-- responsible person (name + email — not necessarily a logged-in app
-- user, so the email is captured directly rather than resolved from
-- app_users) and due date. quick_win_progress (the existing free-text
-- status/percent log) is untouched and keeps working alongside this.
--
-- overdue_notified_at records when the notify-overdue-tasks Edge
-- Function last emailed the responsible person + admins about a task
-- that's still open past its due date, so a task is only ever emailed
-- about once instead of every day it stays overdue.
--
-- Same admin-only write model as the rest of this project's execution
-- tracking (quick_win_progress updates are also admin-only in the UI):
-- only an admin can create/update tasks here for now.
-- ============================================================

create table if not exists quick_win_tasks (
    id bigint generated by default as identity primary key,
    project_name text not null,
    title text not null,
    responsible_name text not null,
    responsible_email text not null,
    due_date date not null,
    status text not null default 'باز' check (status in ('باز', 'در حال انجام', 'انجام‌شده')),
    created_by text,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    overdue_notified_at timestamptz
);

create index if not exists quick_win_tasks_project_name_idx
    on quick_win_tasks (project_name);

create index if not exists quick_win_tasks_overdue_check_idx
    on quick_win_tasks (due_date, status, overdue_notified_at);

alter table quick_win_tasks enable row level security;

drop policy if exists "admin full access on quick_win_tasks" on quick_win_tasks;
create policy "admin full access on quick_win_tasks" on quick_win_tasks
    for all using (is_admin()) with check (is_admin());

-- quick_win_tasks is shared project state (like quick_win_decisions /
-- quick_win_progress) — every manager on a project should be able to see
-- its task checklist, even though only an admin can edit it for now.
drop policy if exists "scoped read on quick_win_tasks" on quick_win_tasks;
create policy "scoped read on quick_win_tasks" on quick_win_tasks
    for select using (
        is_admin()
        or exists (
            select 1 from app_users
            where app_users.user_id = auth.uid()
            and app_users.project_name = quick_win_tasks.project_name
        )
    );

-- Needed by the notify-overdue-tasks Edge Function's scheduled cron job
-- (see supabase/setup_overdue_task_cron.sql) to call that function over
-- HTTP on a schedule. Harmless to re-run if already enabled.
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
