-- «متن درخواست مصوبه» — a formal, one-page CEO approval request per
-- project: a fixed formal letter template (rendered entirely by the
-- frontend, not stored) plus the one part that actually varies per
-- request — a short table of مصوبات (resolutions) paired with the
-- matching تعهد پیمانکار (contractor commitment) and نتیجه مورد انتظار
-- (expected result) — and a digital sign-off slot per organization
-- (کارفرما/مشاور/پیمانکار) so each org's own PM can put their name
-- behind the request before it goes up, for real accountability rather
-- than an anonymous document.
--
-- Insert-only per submission, like check_ins/client_reports (a fresh
-- request is a new row, never edited in place) — signatures are the one
-- exception, added afterward via the sign_approval_request() RPC below,
-- which is the ONLY way any signature column is ever written: it verifies
-- server-side (never trusting client-supplied name/email) that the caller
-- actually has user_project_access for that project+organization before
-- writing their own identity and timestamp into that organization's slot.

create table approval_requests (
    id bigint generated by default as identity primary key,
    project_name text not null,
    created_by uuid references auth.users(id),
    created_at timestamptz not null default now(),
    resolutions jsonb not null default '[]'::jsonb,
    signed_by_client jsonb,
    signed_by_consultant jsonb,
    signed_by_contractor jsonb
);

comment on column approval_requests.resolutions is 'Array of {resolution, contractor_commitment, expected_result} — the one part of the formal letter that varies per request.';
comment on column approval_requests.signed_by_client is '{name, email, signed_at} once کارفرما''s PM signs, written only by sign_approval_request(); null until then.';
comment on column approval_requests.signed_by_consultant is 'Same as signed_by_client, for مشاور.';
comment on column approval_requests.signed_by_contractor is 'Same as signed_by_client, for پیمانکار.';

alter table approval_requests enable row level security;

-- Same scope as the existing "scoped read on client_reports" policy: admin,
-- or any manager with access to the project (any organization).
create policy "scoped read on approval_requests" on approval_requests
    for select using (
        is_admin()
        or exists (
            select 1 from user_project_access upa
            where upa.user_id = auth.uid()
              and upa.project_name = approval_requests.project_name
        )
    );

-- Same scope as the current (post-migration-011) client_reports insert
-- policy: any manager on the project, any organization, can author a
-- request — not restricted to کارفرما.
create policy "managers can insert own project approval_requests" on approval_requests
    for insert with check (
        is_admin()
        or exists (
            select 1 from user_project_access upa
            where upa.user_id = auth.uid()
              and upa.project_name = approval_requests.project_name
        )
    );

create policy "admin delete on approval_requests" on approval_requests
    for delete using (is_admin());

-- Deliberately no UPDATE policy: every signature is written exclusively
-- through the SECURITY DEFINER function below, which runs with elevated
-- privilege after its own checks — never through a client-facing RLS
-- UPDATE grant, so a signature can never be forged as "signed by" someone
-- other than the actual caller.
create or replace function sign_approval_request(p_request_id bigint, p_organization text)
returns approval_requests
language plpgsql
security definer
set search_path = public
as $$
declare
    v_request approval_requests;
    v_name text;
    v_email text;
    v_column text;
begin
    if p_organization not in ('کارفرما', 'مشاور', 'پیمانکار') then
        raise exception 'سازمان نامعتبر است';
    end if;

    select * into v_request from approval_requests where id = p_request_id;
    if v_request is null then
        raise exception 'درخواست مصوبه یافت نشد';
    end if;

    if not is_admin() and not exists (
        select 1 from user_project_access upa
        where upa.user_id = auth.uid()
          and upa.project_name = v_request.project_name
          and upa.organization = p_organization
    ) then
        raise exception 'شما دسترسی امضا برای این سازمان در این پروژه را ندارید';
    end if;

    select email, coalesce(nullif(trim(concat(first_name, ' ', last_name)), ''), email)
        into v_email, v_name
        from app_users where user_id = auth.uid();

    v_column := case p_organization
        when 'کارفرما' then 'signed_by_client'
        when 'مشاور' then 'signed_by_consultant'
        when 'پیمانکار' then 'signed_by_contractor'
    end;

    execute format('update approval_requests set %I = $1 where id = $2', v_column)
        using jsonb_build_object('name', v_name, 'email', v_email, 'signed_at', now()), p_request_id;

    select * into v_request from approval_requests where id = p_request_id;
    return v_request;
end;
$$;

grant execute on function sign_approval_request(bigint, text) to authenticated;
